apiVersion: v1
kind: Namespace
metadata:
  name: adoption-system
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: adoptions
  namespace: adoption-system
spec:
  selector:
    matchLabels:
      app: adoptions
  template:
    metadata:
      labels:
        app: adoptions
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: adoptions
        image: adoptions-image
        ports:
        - containerPort: 3000
          name: adoptions
        - containerPort: 3010
          name: adoptions-debug
        env:
          - name: GOMAXPROCS
            valueFrom:
              resourceFieldRef:
                resource: limits.cpu
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
           path: /liveness
           port: 3000
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        readinessProbe:
          httpGet:
           path: /readiness
           port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2

---

apiVersion: v1
kind: Service
metadata:
  name: adoptions
  namespace: adoption-system
spec:
  type: ClusterIP
  selector:
    app: adoptions
