apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/auth/
patches:
  - path: ./dev-auth-patch.yaml
images:
  - name: auth-server-image
    newName: localhost/rmishgoog/auth-server
    newTag: 0.0.1