apiVersion: v1
kind: Service
metadata:
  name: traefik-proxy
  namespace: traefik-system
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      targetPort: web
    - name: websecure
      port: 443
      targetPort: websecure
  selector:
    app: traefik
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-proxy
  namespace: traefik-system
  labels:
    app: traefik
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-sa
      containers:
        - name: traefik
          image: traefik:v3.1.3
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          args:
            - --entrypoints.web.address=:80
            - --providers.kubernetesingress
            - --entrypoints.websecure.address=:443
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443