apiVersion: apps/v1
kind: Deployment
metadata:
  name: adoptions
  namespace: adoption-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adoptions
  template:
    metadata:
      labels:
        app: adoptions
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: adoptions
        image: adoptions-image
        env:
          - name: GOMAXPROCS
            valueFrom:
              resourceFieldRef:
                resource: limits.cpu
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"