apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/adoptions/
patches:
  - path: ./dev-deployment-patch.yaml
  - path: ./dev-service-patch.yaml
images:
  - name: adoptions-image
    newName: localhost/rmishgoog/adoptadog
    newTag: 0.0.1